/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.com.br.gui.ambiente.prefeitura;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sd.com.br.beans.Prefeitura;
import sd.com.br.dao.DaoPrefeitura;
import sd.com.br.gui.ModeloTabela;

/**
 *
 * @author SergioD
 */
public class TodosFuncionarios extends javax.swing.JPanel {

    /**
     * Creates new form TodosFuncionarios
     */
    
    private Prefeitura prefeitura;
    
    public TodosFuncionarios(Prefeitura prefeitura) {
        this.prefeitura = prefeitura;
        initComponents();
        iniciarTabela();
    }
    
    public void iniciarTabela(){
        
        
        
        if(prefeitura.getFuncionarios() != null && prefeitura.getFuncionarios().size() > 0){
            ArrayList dados = new ArrayList();
            String[] colunas = new String[]{"Nome", "CPF", "Email"};
            
            for(int i=0; i < prefeitura.getFuncionarios().size();i++){
                dados.add(new Object[]{ prefeitura.getFuncionarios().get(i).getNome(),
                                        prefeitura.getFuncionarios().get(i).getCpf(),
                                        prefeitura.getFuncionarios().get(i).getEmail()
                                      });
            }
            
            ModeloTabela tabela = new ModeloTabela(dados, colunas);
            jTFuncionarios.setModel(tabela);
            jTFuncionarios.setRowHeight(40);
            jTFuncionarios.getTableHeader().setReorderingAllowed(false);
            
            
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Não foi Encontrado nenhum resultado!");
            jPResultadoFuncionario.setVisible(false);
            revalidate();
            repaint();
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPResultadoFuncionario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncionarios = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Todos os Funcionarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 23, -1, -1));

        jPResultadoFuncionario.setBackground(new java.awt.Color(255, 255, 255));

        jTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTFuncionarios);

        javax.swing.GroupLayout jPResultadoFuncionarioLayout = new javax.swing.GroupLayout(jPResultadoFuncionario);
        jPResultadoFuncionario.setLayout(jPResultadoFuncionarioLayout);
        jPResultadoFuncionarioLayout.setHorizontalGroup(
            jPResultadoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPResultadoFuncionarioLayout.setVerticalGroup(
            jPResultadoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPResultadoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 540, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPResultadoFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFuncionarios;
    // End of variables declaration//GEN-END:variables
}
