/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.com.br.gui.ambiente.admin;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import sd.com.br.gui.Inicio;

/**
 *
 * @author SergioD
 */
public class AmbienteAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AmbienteAdmin
     */
    
    private Inicio inicio;
    
    public AmbienteAdmin(Inicio inicio) {
        this.inicio = inicio;
        initComponents();
        iniciarBotoes();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void iniciarBotoes(){
        Icon iconSair = new ImageIcon("src/main/java/sd/com/br/gui/img/sair.jpg");
        
        jBSair.setIcon(iconSair);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPAreaMenu = new javax.swing.JPanel();
        jBSair = new javax.swing.JButton();
        jBSolicitacoesPendentes = new javax.swing.JButton();
        jBGerenciarEstado = new javax.swing.JButton();
        jBTodasPrefeitura = new javax.swing.JButton();
        jPAreaTroca = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPAreaMenu.setBackground(new java.awt.Color(255, 255, 255));

        jBSair.setToolTipText("Novo Funcionario");
        jBSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBSolicitacoesPendentes.setToolTipText("Novo Funcionario");
        jBSolicitacoesPendentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSolicitacoesPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitacoesPendentesActionPerformed(evt);
            }
        });

        jBGerenciarEstado.setToolTipText("Novo Funcionario");
        jBGerenciarEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGerenciarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerenciarEstadoActionPerformed(evt);
            }
        });

        jBTodasPrefeitura.setToolTipText("Novo Funcionario");
        jBTodasPrefeitura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTodasPrefeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTodasPrefeituraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAreaMenuLayout = new javax.swing.GroupLayout(jPAreaMenu);
        jPAreaMenu.setLayout(jPAreaMenuLayout);
        jPAreaMenuLayout.setHorizontalGroup(
            jPAreaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAreaMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jBSolicitacoesPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGerenciarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBTodasPrefeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPAreaMenuLayout.setVerticalGroup(
            jPAreaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAreaMenuLayout.createSequentialGroup()
                .addGroup(jPAreaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSolicitacoesPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGerenciarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTodasPrefeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPAreaTroca.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPAreaTrocaLayout = new javax.swing.GroupLayout(jPAreaTroca);
        jPAreaTroca.setLayout(jPAreaTrocaLayout);
        jPAreaTrocaLayout.setHorizontalGroup(
            jPAreaTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPAreaTrocaLayout.setVerticalGroup(
            jPAreaTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPAreaTroca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPAreaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAreaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPAreaTroca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:

        dispose();
        new Inicio().setVisible(true);

    }//GEN-LAST:event_jBSairActionPerformed

    private void jBSolicitacoesPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitacoesPendentesActionPerformed
        // TODO add your handling code here:
        
        jPAreaTroca.removeAll();
        SolicitacoesPendentes sp = new SolicitacoesPendentes();
        sp.setVisible(true);
        sp.setBounds(0,0,1366,600);
        jPAreaTroca.add(sp);
        revalidate();
        repaint();
        
    }//GEN-LAST:event_jBSolicitacoesPendentesActionPerformed

    private void jBGerenciarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerenciarEstadoActionPerformed
        // TODO add your handling code here:
        jPAreaTroca.removeAll();
        GerenciarSolicitacao gs = new GerenciarSolicitacao();
        gs.setVisible(true);
        gs.setBounds(0,0,1366,600);
        jPAreaTroca.add(gs);
        revalidate();
        repaint();        
    }//GEN-LAST:event_jBGerenciarEstadoActionPerformed

    private void jBTodasPrefeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTodasPrefeituraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTodasPrefeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmbienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmbienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmbienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmbienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmbienteAdmin(new Inicio()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerenciarEstado;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSolicitacoesPendentes;
    private javax.swing.JButton jBTodasPrefeitura;
    private javax.swing.JPanel jPAreaMenu;
    private javax.swing.JPanel jPAreaTroca;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
